### ISSUE TITLE
Confusion between duration and time on FR

### ISSUE THREAD

**Issue by zsellami** [facebook/duckling#165]
**Trying this sample with FR language**: La réunion durera 1 heure.
**Duckling propose Time and Duration** [{"body":"1 heure","start":18,"value":{"value":1,"hour":1,"type":"value","unit":"hour","normalized":{"value":3600,"unit":"second"}},"end":25,"dim":"duration"},{"body":"1 heure","start":18,"value":{"values":[{"value":"2018-03-16T13:00:00.000-07:00","grain":"hour","type":"value"},{"value":"2018-03-17T01:00:00.000-07:00","grain":"hour","type":"value"},{"value":"2018-03-17T13:00:00.000-07:00","grain":"hour","type":"value"}],"value":"2018-03-16T13:00:00.000-07:00","grain":"hour","type":"value"},"end":25,"dim":"time"}]

**Expected only a Duration match.**

**Comment by patapizza** [comment]
@zsellami Thanks for reporting. Can you try fixing this?

**Comment by souvikg10** [comment]
@patapizza I can fix this, if no one is on it..

**Comment by patapizza** [comment]
I do. You're right, we'd need sentence-level features for disambiguating between "il est 5 heures" (`Time`) and "ca durera 5 heures" (`Duration`).
Sentence-level features are out of scope for Duckling.

@zsellami If you're looking for durations/times only, you can specify that as a filter. Otherwise, look if the text span is the same and do some filtering on your end.
