### ISSUE TITLE
Numbers interval

### ISSUE THREAD

**Issue by RomainWilbert** [facebook/duckling#187]
Hi !
First I want to thank you for sharing this great library !
Passing number dimension to the API call , I can't have results when entering simple numbers intervals such as "from 9 to 10", "between 1 and 3"...although it works when I add some unit value (distance, currency).
Is there precise documentation on what syntax/dimensions are supported for intervals ? I looked at #76  but I wish I had a straight answer.
Thanks

**Comment by panagosg7** [comment]
Hi @RomainWilbert! Number intervals are interpreted in the context of the various dimensions (distance, time, etc) because they can be highly specialized based on the particular case. For example,  an interval "from 9am to 10pm" makes sense as a time interval but not as a distance one. So these are handled by rules specific to each dimension (unit).

AFAIK there is no standalone documentation of the supported syntax. A workaround for now would be to extract the supported cases by looking at the `name` field of each `Rule` in the relevant Rule.hs file (e.g. https://github.com/facebook/duckling/blob/master/Duckling/Time/EN/Rules.hs).

**Comment by patapizza** [comment]
Oops, duplicate with https://github.com/facebook/duckling/issues/352.
