### ISSUE TITLE
[Amount-of-money] - Internationalisation issue

### ISSUE THREAD

**Issue by souvikg10** [facebook/duckling#214]
Hi guys,
I noticed for FR and NL, when you provide amount of money in NL or FR locale in decimal, the value is coming in English format.

If you write 20,42 euros in FR or NL, the value is 20.42

It could be internationalised.

**Comment by patapizza** [comment]
Hi @souvikg10, this is expected: the value returned is a number, not a string. The underlying notation which uses decimal separator is independent of Duckling.

**Comment by paddotk** [comment]
I'd like to reopen this. I have the same issue, but instead of `'20,42'` as input, the input `'20.42'` outputs the number `20.42`, which I think is what @souvikg10 meant to say. But, Dutch and French use the comma as a decimal separator, not a period.

@patapizza I'm not sure what you mean. The input is/can be a string, and I believe Duckling should take locale into account with these separators, right?
