### ISSUE TITLE
More documentation about custom dimensions

### ISSUE THREAD

**Issue by ropottnik** [facebook/duckling#236]
This is a follow-up to https://github.com/facebook/duckling/issues/231. 

The advice @chinmay87 gave me was to set up my own custom dimension in order to get my vision of geographic units working. 

What would be of great help to people creating custom dimensions are the following examples: 
* adding a custom dimension to a server like the one started in https://github.com/facebook/duckling/blob/master/exe/ExampleMain.hs
* using a custom dimension that also consists of other dimensions (such as `Temperature` that utilizes `Numeric`. 

Thanks in advance!

**Comment by chinmay87** [comment]
Thanks for the feedback @ropottnik. 
@zliu41 - Do you think you can help with that?

**Comment by patapizza** [comment]
@ropottnik Custom dimensions are still early so we're iterating on them to see what works best; we'll publish the documentation once it settles for a while.

In the meantime, here are some pointers for your specific questions:
* I'll update the `ExampleMain.hs` file to show how to read custom dimensions.
* To build a custom dimension on top of existing dimensions, you'll need to update `dimDependents` to have all depending dimensions recursively. So to use `Time`, you'd do:
```
dimDependents _ = HashSet.fromList
  [This Duration, This Numeral, This Ordinal, This Time, This TimeGrain]
```

**Comment by cspencer** [comment]
Perhaps someone can offer some more clarification on adding a custom dimension to the ExampleMain.hs file.  Here's what I've done so far:

1. Created a MyDimension.hs file from the definitions for the MyDimension type in exe/CustomDimensionExample.hs

2. Added the new file in duckling.cabal so that everything gets compiled

3. Imported the MyDimension's constructor in the ExampleMain.hs file with:

  `import MyDimension (MyDimension(..))`

4. Uncommented line 116 of ExampleMain.hs, so that it looks like:
  `[ ("my-dimension", This (CustomDimension MyDimension))
    ]`

The new type is still not showing up when ExampleMain.hs is recompiled - have I missed something obvious here?

**Comment by patapizza** [comment]
@cspencer Do you have a fork I can look into?

**Comment by cspencer** [comment]
@patapizza Sure - I've forked and pushed everything [here](https://github.com/cspencer/duckling).

Thanks so much for the quick response - I'm keen to use duckling in one of our projects, and would love to figure this out.

**Comment by patapizza** [comment]
@cspencer Cloned a fresh copy of the repo and could successfully get entities from `MyDimension`:

Starting the server:
```
$ stack build :duckling-example-exe && stack exec duckling-example-exe
...
no port specified, defaulting to port 8000
Listening on http://0.0.0.0:8000
```

Testing `MyDimension`:
```
$ curl -XPOST http://localhost:8000/parse --data 'locale=en_XX&text=my dimension&dims=["my-dimension"]'
[{"body":"my dimension","start":0,"value":{"value":"42,True,hello world"},"end":12,"dim":"MyDimension","latent":false}]
```

**Comment by cspencer** [comment]
@patapizza My fault - I missed the part where I needed to pass in a 'dims' parameter in the request.

Thanks for the assistance!
