### ISSUE TITLE
Using python to get parsing result

### ISSUE THREAD

**Issue by chiapas** [facebook/duckling#260]
Currently, I have to use 

    from subprocess import PIPE, run

    text = "from 9am to 10am"
    command = "curl -XPOST http://127.0.0.1:9999/parse --data \"text={}\"".format(text)
    result = run(command, stdout=PIPE, stderr=PIPE, universal_newlines=True, shell=True)

But python -> shell -> duckling -> shell -> python, it's very slow. It's even much slower than this duckling python wrapper [FraBle/python-duckling](https://github.com/FraBle/python-duckling), where the actual duckling is in .jar files.

I don't know Haskell at all. Could you help me to find a performant solution to get duckling result from python? Thanks.

**Comment by sebastianmika** [comment]
You might want to start here: https://github.com/sebastianmika/pyduckling. It is a bit outdated and I cannot support you in making it run. But at least this way my take at getting a "native" duckling interface from python. And it is limited to times only etc. but might be expanded.

Obviously it would be much better if such a wrapper would be part of duckling itself :-)

**Comment by r-wheeler** [comment]
@sebastianmika I used the above to write bindings and it worked very well as a starting point.

**Comment by chiapas** [comment]
Hi, could you share your code and the usage?

**Comment by chiapas** [comment]
> 
> 
> @sebastianmika I used the above to write bindings and it worked very well as a starting point.

@r-wheeler , could you share your code and the usage?

**Comment by chessai** [comment]
Other pointers aside, at the very least their must be http libraries you can use? I have used the `requests` library in the past and it has worked well. You can build something on top of that (like previous attempts to build a python wrapper for duckling).

Closing since duckling team has no intention of providing a python library at this time, or any point in the future (though this is subject to change)
