### ISSUE TITLE
Duckling date and time parser

### ISSUE THREAD

**Issue by mike23333** [facebook/duckling#264]
I'm creating a bot uses date and time parser. I want to make duckling work where I have two separate entities like a duckling time and duckling date entity instead of one whole one. For example, if user says tuesday but doesn't give time. It will say "What time" then it will get the time and vice versa if they say the time it will ask for day.

How can I do this?

**Comment by patapizza** [comment]
Hi @mike23333,

You can use the `grain` returned in the response for this.
If the `grain` is lower than `day` (i.e. `minute` or `second`), then it's a time; otherwise it's a date. Strictly speaking, only a grain of `day` is an actual date; for the higher grains you might want to ask the end user to be more specific.

Hope this helps.
