### ISSUE TITLE
Returned entities missing certain dimensions

### ISSUE THREAD

**Issue by alhuang10** [facebook/duckling#292]
I found that the output from the following query:
```json
{ "text": "increase temperature by 10",
"dims": ["number", "time"],
"latent": "True"}
```
consists only of one non-latent time dimension result due to the **ruleIntervalBy** Rule. No number dimension returned despite the explicit specification in "dims". 

On the other hand, the query with "by" removed:
```json
{ "text": "increase temperature 10",
"dims": ["number", "time"],
"latent": "True"}
```
has 2 result dimensions: number and time (latent).

It seems like **ruleIntervalBy** is suppressing the number dimension output. Is that what is happening here? Could you point me in the right direction for modifying the code such that in the first case we return a number dimension result in addition to the time dimension?

Thanks in advance for the help!

**Comment by patapizza** [comment]
Hi @alhuang10,

Duckling will only return the top-level entities. The reason is that when you say things like `between 8 and 10 tomorrow morning`, there are a bunch of intermediate tokens that aren't relevant.
Duckling [returns the parsed tree](https://github.com/facebook/duckling/blob/master/Duckling/Types.hs#L291) that you can traverse to find intermediate tokens, e.g. `Numeral`.

Hope this helps.
