### ISSUE TITLE
duckling-example-exe.EXE

### ISSUE THREAD

**Issue by lansedebing** [facebook/duckling#309]
F:\duckling-master>stack exec duckling-example-exe
duckling-example-exe.EXE: /usr/share/zoneinfo/: getDirectoryContents:findFirstFile: does not exist (??????????????????????)

**Comment by SalAlba** [comment]
Run the command below 

``` bash
$  stack exec duckling-example-exe
```
get this error or warning 

```
Executable named duckling-example-exe not found on path:[
  "/root/Mateo/duckling/.stack-work/install/x86_64-linux-tinfo6/lts-9.10/8.0.2/bin",
   "/root/.stack/snapshots/x86_64-linux-tinfo6/lts-9.10/8.0.2/bin",
    "/root/.stack/compiler-tools/x86_64-linux-tinfo6/ghc-8.0.2/bin",
     "/root/.stack/programs/x86_64-linux/ghc-tinfo6 8.0.2/bin",
     "/usr/local/sbin",
     "/usr/local/bin",
     "/usr/sbin",
    "/usr/bin",
    "/sbin",
    "/bin", 
     "/usr/games",
    "/usr/local/games",
     "/snap/bin"]

```

**Comment by njean78** [comment]
The issue seems to be related to loadTimeZoneSeries that assumes Olson files in /usr/share/zoneinfo as clearly stated in the commented line 34 : 

-- Many linux distros have Olson data in "/usr/share/zoneinfo/"

as quick and very dirty solution I did the following : 

* took zoneinfo files from cygwin dir "/usr/share/zoneinfo/" and copied them on C:/zoneinfo (yes I am running on windows 10)
* brutally modified TimeZone.hs substituting dir with "C:/zoneinfo" (this is 'cause I am lazy and do not remember anything on how to write Haskell code)

After this stack exec duckling-example-exe ran without raising any error

**Comment by mekyush** [comment]
Hi njean78,
Which modification you have made in TimeZone.hs to make it working?

**Comment by SuunnyyGoo** [comment]
Hi, i get another issue while installing duckling : 

stack exec duckling-example-exe
Downloaded lts-14.16 build plan.    
AesonException "Error in $['system-info']: key \"os\" not present"

I'm working on Ubuntu 18.04, does anyone know how to go through this issue ?

**Comment by patapizza** [comment]
@njean78 Provided a workaround for Windows users. Relevant thread: https://github.com/golang/go/issues/21881

**Comment by jonathborg** [comment]
Execute the command out of duckling cloned repo dir.
```
cd .. && stack exec duckling-example-exe
```
