### ISSUE TITLE
Description on how to setup a new language?

### ISSUE THREAD

**Issue by FabianL1** [facebook/duckling#431]
I used the Dockerfile provided in the repo and I could not find any information on how to setup up another language (e.g. german). Or does german simply not work?

**Comment by patapizza** [comment]
Hi @FabianL1,

How are you issuing requests to your service? The Dockerfile sets up Duckling, which comes in all available languages.

**Comment by chessai** [comment]
Can you define "set up"? Do you mean "instantiate the duckling executable to a state such that it supports a given language"?

If you are issuing requests to a running duckling service, you can set the locale via HTTP. example cURL (also in readme):
```
curl -XPOST http://0.0.0.0:8000/parse --data 'locale=de&text=das ist nicht mein bier'
```

Closing as I think this is just due to confusion. Feel free to re-open if we are interpreting you incorrectly.
