### ISSUE TITLE
Issue while Deploying in Heroku

### ISSUE THREAD

**Issue by mekyush** [facebook/duckling#438]
Hi @patapizza 
I have deployed this app in Heroku platform and it's working fine. But when we call parse api it's giving error "Connection closed without response". This error is coming due to request timeout. Heroku need atleast 30 second configured for a application. But i have seen that our application have 20 second for request timeout.

So, Could you please let me know where i can configure custom request timeout second in application.

**Comment by eutampieri** [comment]
@mekyush can you share the Procfile and the buildpack?
I'm using [this buildpack](https://github.com/nejstastnejsistene/heroku-buildpack-stack) and thin Procfile
```
web: stack exec -- duckling-example-exe --port $PORT
```
but the deployment fails:
```
remote: -----> Setting up stack
remote:        Downloading lts-9.10 build plan ...
remote:        Downloaded lts-9.10 build plan.
remote:        Caching build plan
remote:        Updating package index Hackage (mirrored at https://github.com/commercialhaskell/all-cabal-hashes.git) ...
remote:        Fetching package index ...
remote:        Fetched package index.
remote:        Populating index cache ...
remote:        Populated index cache.
remote:        Preparing to install GHC to an isolated location.
remote:        This will not interfere with any system-level installation.
remote:        Preparing to download ghc-8.0.2 ...
remote:        ghc-8.0.2: download has begun
remote:        ghc-8.0.2:   45.02 MiB / 107.55 MiB ( 41.86%) downloaded...
remote:        ghc-8.0.2:   84.22 MiB / 107.55 MiB ( 78.31%) downloaded...
remote:        ghc-8.0.2:  107.55 MiB / 107.55 MiB (100.00%) downloaded...
remote:        Downloaded ghc-8.0.2.
remote:        Unpacking GHC into /tmp/stack-setup32572/ ...
remote:        Configuring GHC ...
remote:        Installing GHC ...
remote:        Installed GHC.
remote:        stack will use a locally installed GHC
remote:        For more information on paths, see 'stack path' and 'stack exec env'
remote:        To use this GHC and packages outside of a project, consider using:
remote:        stack ghc, stack ghci, stack runghc, or stack exec
remote: -----> Installing app
remote:        Invalid package ID: "array-0.5.1.1 base-4.9.1.0 binary-0.8.3.0 bytestring-0.10.8.1"
remote:  !     Push rejected, failed to compile Stack app.
```

**Comment by chessai** [comment]
I think there is a simple fix. Change the following lines:
```haskell
  p <- lookupEnv "PORT"
  conf <- commandLineConfig $
    maybe defaultConfig (`setPort` defaultConfig) (readMaybe =<< p)
```
to (note that you will need to enable `{-# LANGUAGE TypeApplications #-}` at the top of the file):
```haskell
p <- readMaybe @Int <$> lookupEnv "PORT"
t <- readMaybe @Int <$> lookupEnv "TIMEOUT"
conf <- commandLineConfig $
  let setPort_ = maybe id setPort p
       setTimeout_ = maybe id setDefaultTimeout t
  in setPort_ . setTimeout_ $ defaultConfig
```


Could you provide more details and re-open if you're still experiencing this?

1. What procfile are you using?
2. What buildpack are you using?
3. Heroku requires that an HTTP api reply with at least 1 byte of a response within 30 seconds, and you say "our application has 20 seconds for a request timeout". Which application, duckling? 
4. Have you confirmed that your heroku instance hasn't been configured to 20 seconds instead of the default 30? The error you're getting is from heroku, not duckling. [See this explanation](https://devcenter.heroku.com/articles/error-codes#:~:text=in%20Ruby%20(MRI)-,H13%20%2D%20Connection%20closed%20without%20response,without%20writing%20anything%20to%20it.)

```

```
