### ISSUE TITLE
Possible solution for the issue  #420

### ISSUE THREAD

**Issue by 3NFBAGDU** [facebook/duckling#442]
Hello,

I think I've found the solution for this issue https://github.com/facebook/duckling/issues/420 and I wanna make a pull request, so I want to know if my solution will be accepted.

in ``document.hs`` we have the code:
```
isRangeValid :: Document -> Int -> Int -> Bool
isRangeValid doc start end =
  -- (start == 0) &&
  -- (end == length doc)
  (start == 0 || 
      isDifferent (doc ! (start - 1)) (doc ! start)) &&
  (end == length doc ||
      isDifferent (doc ! (end - 1)) (doc ! end))

  where
    charClass :: Char -> Char
    charClass c
      | Char.isLower c || Char.isUpper c   = 'c'
      | Char.isDigit c = 'd'
      | otherwise = c
    isDifferent :: Char -> Char -> Bool
    isDifferent a b = charClass a /= charClass b
```

 in case-insensitive languages like Georgian we have the following problem: 
```
| Char.isLower c || Char.isUpper c || Char.isAlpha c  = 'c'
      | Char.isDigit c = 'd'
      | otherwise = c
``` 
this condition always returns the otherwise=c in case-insensitive languages (since Char.isLower Char.isUpper both will be false). So when in ``Rules.hs`` I have 'ათი' in Hashmap my code will get a match of 'ათი' from 'პათიზ' which is wrong. That's why I changed those functions with Char.isAlpha

I solved this problem change condition like this : 
```
      | Char.isLower c || Char.isUpper c || Char.isAlpha c  = 'c'
      | Char.isDigit c = 'd'
      | otherwise = c
```
this change solved the problem now from 'პათიზ'  duckling does not get a match of 'ათი'.

**Comment by haoxuany** [comment]
This looks right to me, but it took me quite a bit to actually dig through this to figure out why we care about `isRangeValid`. This entire segment appears to be the root cause of #313 (aka really sketchy code, it should be cleaned up and clarified, because for repeated consecutive characters this will give the exact same character class, which is why it sometimes fails).
My 2cents: yes, it would be great if you can submit a pull request for this, and we will accept it. Please put in the same details in the pull request as you have here. 😄 
In the longer run though, we really really should get rid of the use of `isRangeValid`. There should be a better way of doing this, since this is undoubtedly a long standing bug. I'd dig into this, but I don't quite have to bandwidth and time to do that yet.
cc @patapizza

**Comment by 3NFBAGDU** [comment]
Hi, Thank You for the response.
After I added `isAlpha()` in `isRangeValid` function I have another problem here. Some test cases fail in the following languages: KO, KM, ZH_TW, ZH_MO, ZH_HK, ZH_CN, AR, HE, JA. 
So I can't submit a pull request. I don't know these languages  Maybe these test cases are fit on this bug, and this is a cause of this problem.

**Comment by haoxuany** [comment]
Ah darn, those locales are CYK locales, and probably don't work very nicely with `isAlpha` or `isLetter`.
My 2cents on the issue is that this entire function for back searching utf16 match locations from utf8 is crazy problematic in the first place. I would dig into and rewrite the way we get match results from PCRE if I had the time, which sadly, I'm running a bit short of.
@patapizza : can we add this issue into planning? This requires a nontrivial fix, and is a root source of at least two bugs now.

**Comment by patapizza** [comment]
Thanks for digging into this.

`isRangeValid` actually allows the engine to find all the matches concurrently, and then find the best one after filtering out the ones that don't work -- until we've exhausted all tokens generations, we can't know for sure which ones need to be discarded. So we can't get rid of it easily - but we definitely need to look deeper into how to better support the aforementioned character sets.
