### ISSUE TITLE
Found time expression in "deploy@ip-10-1-70-113.ec2.internal"

### ISSUE THREAD

**Issue by resec** [facebook/duckling#452]
The "10-1-70" inside "deploy@ip-10-1-70-113.ec2.internal" is intercepted as date "1970-10-01", maybe we should avoid intercepting "-" appended for pattern "month-day-year" ?

**Comment by chessai** [comment]
I'm not sure we can do this in general.

If you are using the example application, and this is the entirety of the text being passed, I would perhaps make sure to not include the `time` dimension in your query.

If you are using duckling the library, make sure you are not passing in `Seal Time`.

The only way I can see this working is if you add a custom dimension for hostnames or something like that.
If you give more details about how you are using duckling, maybe I can help you out. But, I'm going to close this issue as-is, because as stated this issue is not something duckling team will take action on.
