### ISSUE TITLE
Unable to install Duckling server on a virtual machine without internet connectivity

### ISSUE THREAD

**Issue by neethuvv15** [facebook/duckling#508]
In the  https://github.com/facebook/duckling it is given that we should build the duckling source code using **stack build** command and when we execute the command it will download the required packages. But in my VM i dont have internet connectivity so i was not able to perform stack build. I am attaching the screenshot of the error I received while executing the stack build command. It will be very grateful if I can get the steps to install duckling without using the internet.

![duckling_build_error](https://user-images.githubusercontent.com/65273460/86883510-bbf09d80-c10f-11ea-9ca6-83ac243df3ea.PNG)

**Comment by chessai** [comment]
Hi @neethuvv15! While this is out of scope for the duckling project to provide, I can give some advice:

The only way to do this is to vendor your dependencies (have them locally on the file system), since all haskell dependencies are fetched over the network by default, unless otherwise specified. For stack, you can modify duckling's stack.yaml to point to local packages. For example, in duckling's stack.yaml:

```
resolver: lts-14.20

packages:
- '.'
- dependencies/vector

extra-deps: []

flags: {}

extra-package-dbs: []
```

Assuming a subdirectory of your local duckling named `dependencies`, it will look in the `vector` subdirectory for a package (in this case `vector`) and build the package if it is a dependency of your project. This is the easiest way to override dependencies without network access. (I assume you can get files onto the VM, since you were able to get duckling on there).

Good luck, and don't hesitate to ask questions here!
