### ISSUE TITLE
High CPU load when idle

### ISSUE THREAD

**Issue by anne-38** [facebook/duckling#556]
We run duckling on kubernetes. What we're observing is a constant CPU load, even when idle. It is around 10-15% of 1 CPU, which seems high for an application that only has to say quack! every ten seconds or so ;) (this is the response to k8s livenessProbe). That makes it one of the top CPU users on our cluster.

When I run the docker image locally, I can see CPU spiking to around 20% (of a single thread) on a request to /, staying at that level for a little over a minute, and then settling back down to 0.

Is this a known issue for either haskell or duckling? Is there anything that I can do to improve this?

**Comment by chessai** [comment]
Are you running the example application?

If you are running the example application, there's no guarantee of performance there. It is just a tiny application written to be usable. If I had to guess what was wrong, it's probably a bug in the snap framework that's being used.

**Comment by anne-38** [comment]
I built the docker image with the Dockerfile of the project and it invokes the example application. So, what else should I run instead of the example application? I'm a complete Haskell noob, so you may have to spell it out for me.

**Comment by chessai** [comment]
@anne-38 What I mean to say is that, there is currently no open source executable other than the example application, which is intended for nothing other than users to try out duckling. So, there are a few possibilities:

1. The bug is investigated (probably reported to snap repo - i don't see from looking out duckling's example exe code why there would be this issue)
2. Duckling team creates and maintains one
3. User (such as yourself) writes one and either hosts it elsewhere or PRs it to duckling

I can see if I can fit in (2) next week. In the meantime, if you or a teammate feel like taking a crack at it, then don't hesitate. Feel free to ask any questions if you do.

**Comment by anne-38** [comment]
Thank you for the extra info. I'll see what I can do wrt to writing my own executable. However I'm not hopeful about the outcome in the short term. As said I'm a complete Haskell newbie and within our organisation there are no Haskell programmers that I am aware of.

**Comment by anne-38** [comment]
Using the +RTS -t -RTS options I could find out that it is indeed the garbage collection that causes high CPU. Although the performance of duckling is very good (roughly 200 req/s per thread), it's quite incredible how much garbage collection simple quack! causes.

I now run the application with +RTS -Iw300 -RTS options on k8s, making sure that idle garbage collections only occur less frequent than once per 5 minutes. That has greatly reduced cpu usage. Some performance testing done locally did not yield any measurable difference in throughput or memory usage.

@chessai, thanks for the responses.

I will close the issue.
