### ISSUE TITLE
Support Persian(fa) Languages

### ISSUE THREAD

**Issue by AmirMohamadBabaee** [facebook/duckling#712]
First, thanks for your fantastic repo. Could you let me know if you plan to support the Persian language?

**Comment by chessai** [comment]
Farsi numerals are supported: https://github.com/facebook/duckling/blob/main/Duckling/Numeral/FA/Rules.hs

But it looks like most dimensions do not have Farsi support.

Typically, new language support in Duckling is added by third-party developers and not the duckling team, since the Duckling team is small and has fluent understanding of a minimal set of languages (English, French, Mandarin, Cantonese).

If you would like to see more Farsi support, I encourage you to take a stab at it!

**Comment by AmirMohamadBabaee** [comment]
Thanks for your quick reply.
I am very eager to contribute to this wonderful project, but I have no experience in Haskell. Is there a template for defining Persian rules in other dimensions?

**Comment by stroxler** [comment]
For the code itself, your best bet would probably be to look at some of the existing implementations to understand how rules are laid out.

I'd recommend starting with some dimension other than `Time`, those rules tend to be very complex but others are usually much simpler.

**Comment by AmirMohamadBabaee** [comment]
Thanks, @stroxler
